
## Coursera assignment "Inverse Matrix Cache" week 3 by Alexander Jansma on 2019-01-23

## makeCacheMatrix takes a matrix as input on 'x', by use of the set() function. X is stored in get(), and is then solved in cacheSolve via data <- x$get, then solve(x), and stored to variable 'z', also to x$setInv(z). 

##The value of X can be retrieved from makeCacheMatrix by the cacheSolve function due to the <<- operator, which stores the value of x in the global environment. 

## Setting setInv in cacheSolve, will store the solved matrix into z by the <<- operator (lexical scoping), which is then fed to getInv(). getInv() is subsequently called in the cacheSolve function to check if a value has already been computed for the inverse of input matrix 'x'.

makeCacheMatrix <- function(x = matrix()) {
	z <- NULL;
	
	## function to set a value to y and pass to x, the input matrix. E.g. variable$set(matrix(1:4, 2)). The value of 'x' is defined in the global environment due to <<-, which allows it to be taken as input in the cacheSolve() function.
	set <- function(y) {
		x <<- y;
		z <<- NULL;
	}
	
	## function that passes value of the matrix input to makeCacheMatrix
	get <- function() x;
	
	## function used to set 'z', that takes as input variable 'inv', which is defined in cacheSolve (lexical scoping operator <<-) also as 'z'. As such, inv / 'z' is calculated in cacheSolve and input to setInv by x$setInv(z) in cacheSolve (inverse of matrix x).
	setInv <- function(inv) z <<- inv;
	
	## function that stores the value of 'z', or the solved matrix, which if it has a value, the inverse of which is not calculated again in the cacheSolve function. Can then be called by x$getInv() to retrieve the value of the inverse matrix. 
	getInv <- function() z;
	
	# list that stores the seperate functions and corresponding numeric values generated by the function for the next iteration, instead of storing the values within the functions.
	list(set = set, get = get, setInv = setInv, getInv = getInv);
	
}


## CacheSolve is a function to solve or compute the inverse of matrix x. If the matrix had already been solved, cacheSolve checks if x$getInv() contains a value.  If there is no inverse available yet, the matrix is retrieved from x$get(), which contains the matrix x as defined by x$set() in makeCacheMatrix(). Then, the inverse of the matrix is calculated and is set to setInv(z); or stored in the cache / makeCacheMatrix().

cacheSolve <- function(x, ...) {
		
	z <- x$getInv();
	if(!is.null(z)) {
		message("retrieving data from cache...");
		return(z);
	}
	    ## Return a matrix that is the inverse of 'x'. 
	   	data <- x$get();
		z <- solve(data, ...);
        x$setInv(z);
        z;
}
